// Events data for the Campus Connect Portal

// Sample events data
const eventsData = [
    {
        id: 1,
        title: "Annual Music Festival",
        category: "Cultural",
        categoryClass: "info",
        status: "Registration Open",
        statusClass: "success",
        description: "Join us for a night of amazing performances by talented students and guest artists. The Annual Music Festival is one of the most anticipated events of the year, featuring performances across various genres including classical, rock, pop, and jazz. This year's festival will also feature special guest performances by renowned artists from the music industry.",
        date: "May 15, 2023",
        time: "6:00 PM - 10:00 PM",
        location: "Campus Auditorium",
        organizer: "Student Cultural Committee",
        image: "IMG/poster for an annual music festival.png",
        registrationDeadline: "May 10, 2023",
        availableSeats: 150,
        schedule: [
            { time: "6:00 PM - 6:30 PM", activity: "Opening Ceremony", location: "Main Stage" },
            { time: "6:30 PM - 7:30 PM", activity: "Classical Music Performances", location: "Main Stage" },
            { time: "7:30 PM - 8:30 PM", activity: "Band Performances", location: "Main Stage" },
            { time: "8:30 PM - 9:30 PM", activity: "Guest Artist Performance", location: "Main Stage" },
            { time: "9:30 PM - 10:00 PM", activity: "Closing Ceremony & Awards", location: "Main Stage" }
        ],
        contactEmail: "music@campusconnect.edu",
        contactPhone: "(123) 456-7890",
        relatedEvents: [6, 3]
    },
    {
        id: 2,
        title: "Tech Hackathon 2023",
        category: "Technology",
        categoryClass: "warning",
        status: "Registration Open",
        statusClass: "success",
        description: "A 48-hour coding competition to solve real-world problems with innovative solutions. The Tech Hackathon brings together students from various disciplines to collaborate and create technological solutions for challenges faced by our community. Participants will have access to mentors from leading tech companies and resources to bring their ideas to life.",
        date: "June 10-12, 2023",
        time: "Starts at 9:00 AM on June 10",
        location: "Tech Building",
        organizer: "Computer Science Department",
        image: "IMG/poster for Tech Hackathon 2023.png",
        registrationDeadline: "June 5, 2023",
        availableSeats: 100,
        schedule: [
            { time: "June 10, 9:00 AM - 10:00 AM", activity: "Registration & Team Formation", location: "Tech Building Lobby" },
            { time: "June 10, 10:00 AM - 11:00 AM", activity: "Opening Ceremony & Problem Statements", location: "Lecture Hall 1" },
            { time: "June 10, 11:00 AM - June 12, 9:00 AM", activity: "Hackathon in Progress", location: "Tech Building Labs" },
            { time: "June 12, 9:00 AM - 12:00 PM", activity: "Project Presentations", location: "Lecture Hall 1" },
            { time: "June 12, 2:00 PM - 3:00 PM", activity: "Awards Ceremony", location: "Lecture Hall 1" }
        ],
        contactEmail: "hackathon@campusconnect.edu",
        contactPhone: "(123) 456-7891",
        relatedEvents: [5, 4]
    },
    {
        id: 3,
        title: "Career Development Seminar",
        category: "Career",
        categoryClass: "success",
        status: "Registration Open",
        statusClass: "success",
        description: "Learn from industry experts about career opportunities and professional development. This seminar will feature speakers from various industries who will share insights on career paths, job market trends, and skills required for success in today's competitive environment. There will also be networking opportunities with potential employers and resume review sessions.",
        date: "May 25, 2023",
        time: "10:00 AM - 4:00 PM",
        location: "Business School",
        organizer: "Career Services Center",
        image: "IMG/poster for Career Development Seminar.png",
        registrationDeadline: "May 20, 2023",
        availableSeats: 200,
        schedule: [
            { time: "10:00 AM - 10:30 AM", activity: "Welcome & Introduction", location: "Business School Auditorium" },
            { time: "10:30 AM - 12:00 PM", activity: "Industry Panel Discussion", location: "Business School Auditorium" },
            { time: "12:00 PM - 1:00 PM", activity: "Lunch Break & Networking", location: "Business School Lobby" },
            { time: "1:00 PM - 2:30 PM", activity: "Workshop: Resume Building & Interview Skills", location: "Seminar Rooms" },
            { time: "2:30 PM - 4:00 PM", activity: "Career Fair & Networking", location: "Business School Lobby" }
        ],
        contactEmail: "careers@campusconnect.edu",
        contactPhone: "(123) 456-7892",
        relatedEvents: [5, 1]
    },
    {
        id: 4,
        title: "Inter-College Sports Meet",
        category: "Sports",
        categoryClass: "danger",
        status: "Registration Open",
        statusClass: "success",
        description: "Annual sports competition featuring various games and athletic events between colleges. The Inter-College Sports Meet is a three-day event that brings together athletes from various colleges to compete in sports like basketball, football, volleyball, athletics, swimming, and more. Come support your college teams and witness exciting competitions.",
        date: "May 20-22, 2023",
        time: "8:00 AM - 6:00 PM daily",
        location: "Sports Complex",
        organizer: "Sports Department",
        image: "IMG/poster for Inter-College Sports Meet.png",
        registrationDeadline: "May 15, 2023",
        availableSeats: 500,
        schedule: [
            { time: "May 20, 8:00 AM - 9:00 AM", activity: "Opening Ceremony", location: "Main Stadium" },
            { time: "May 20, 9:00 AM - 6:00 PM", activity: "Preliminary Rounds", location: "Various Venues" },
            { time: "May 21, 8:00 AM - 6:00 PM", activity: "Quarter & Semi Finals", location: "Various Venues" },
            { time: "May 22, 8:00 AM - 4:00 PM", activity: "Finals", location: "Various Venues" },
            { time: "May 22, 4:00 PM - 6:00 PM", activity: "Closing Ceremony & Prize Distribution", location: "Main Stadium" }
        ],
        contactEmail: "sports@campusconnect.edu",
        contactPhone: "(123) 456-7893",
        relatedEvents: [2, 6]
    },
    {
        id: 5,
        title: "Research Methodology Workshop",
        category: "Academic",
        categoryClass: "primary",
        status: "Registration Open",
        statusClass: "success",
        description: "Learn advanced research methodologies and tools for academic research projects. This workshop is designed for graduate students and faculty members interested in enhancing their research skills. Topics covered include research design, data collection methods, statistical analysis, qualitative research techniques, and research ethics. Participants will also get hands-on experience with research tools and software.",
        date: "June 5, 2023",
        time: "9:00 AM - 5:00 PM",
        location: "Science Building",
        organizer: "Research Department",
        image: "IMG/poster for Research Methodology Workshop.png",
        registrationDeadline: "June 1, 2023",
        availableSeats: 80,
        schedule: [
            { time: "9:00 AM - 9:30 AM", activity: "Registration & Welcome", location: "Science Building, Room 101" },
            { time: "9:30 AM - 11:00 AM", activity: "Session 1: Research Design & Methodology", location: "Science Building, Room 101" },
            { time: "11:00 AM - 12:30 PM", activity: "Session 2: Data Collection Methods", location: "Science Building, Room 101" },
            { time: "12:30 PM - 1:30 PM", activity: "Lunch Break", location: "Science Building Cafeteria" },
            { time: "1:30 PM - 3:00 PM", activity: "Session 3: Data Analysis Techniques", location: "Computer Lab" },
            { time: "3:00 PM - 4:30 PM", activity: "Session 4: Research Ethics & Publication", location: "Science Building, Room 101" },
            { time: "4:30 PM - 5:00 PM", activity: "Q&A and Closing", location: "Science Building, Room 101" }
        ],
        contactEmail: "research@campusconnect.edu",
        contactPhone: "(123) 456-7894",
        relatedEvents: [3, 2]
    },
    {
        id: 6,
        title: "Annual Dance Competition",
        category: "Cultural",
        categoryClass: "info",
        status: "Registration Open",
        statusClass: "success",
        description: "Showcase your dancing talent in various styles including contemporary, classical, and folk. The Annual Dance Competition is open to all students who are passionate about dance. Participants can compete in solo, duet, or group categories across different dance styles. The event will be judged by professional dancers and choreographers, with exciting prizes for the winners.",
        date: "June 15, 2023",
        time: "5:00 PM - 9:00 PM",
        location: "Cultural Center",
        organizer: "Dance Club",
        image: "img/poster for Annual Dance Competition (1).png",
        registrationDeadline: "June 10, 2023",
        availableSeats: 120,
        schedule: [
            { time: "5:00 PM - 5:30 PM", activity: "Opening Ceremony", location: "Cultural Center Auditorium" },
            { time: "5:30 PM - 6:30 PM", activity: "Solo Performances", location: "Cultural Center Auditorium" },
            { time: "6:30 PM - 7:30 PM", activity: "Duet Performances", location: "Cultural Center Auditorium" },
            { time: "7:30 PM - 8:30 PM", activity: "Group Performances", location: "Cultural Center Auditorium" },
            { time: "8:30 PM - 9:00 PM", activity: "Results & Prize Distribution", location: "Cultural Center Auditorium" }
        ],
        contactEmail: "dance@campusconnect.edu",
        contactPhone: "(123) 456-7895",
        relatedEvents: [1, 4]
    }
];